### ISSUE TITLE
About the derivation of the formula

### ISSUE THREAD

**Issue by jingfengou** [yulun-rayn/variational-causal-inference#1]
Hello! I find the method you have adopted very meaningful and the mathematical theory is complete, so I am very interested. Forgive my limited level, would like to ask a picture of Chinese 8 to 9 how to get? In addition, what is the specific meaning of p(T |X)?
![1715674637045](https://github.com/yulun-rayn/variational-causal-inference/assets/142006492/4273d810-7e19-47c5-b694-54c7974e23c8)

**Comment by yulun-rayn** [comment]
Hi, thanks for the compliment! This is just factorization of the conditional probability on the numerator based on our graphical model. I recommend searching "d-separation" and "factorization of conditional probability" on google, youtube or stackoverflow (e.g. https://www.youtube.com/watch?v=yDs_q6jKHb0), then you'll get a good sense of it! For p(T | X), search "propensity score" for more details.

**Comment by jingfengou** [comment]
Thank you very much for your detailed response, but I still don't quite understand why a p(Y,T|Z,X) is factored out from equation 9 to equation 10. Could you explain this to me? I would be very grateful!

**Comment by yulun-rayn** [comment]
p(Y', Z, Y, T | X, T') = p(Y' | X, T') p(Z | Y', X, T') p(Y, T | Z, Y', X, T') = p(Y' | X, T') p(Z | Y', X, T') p(Y, T | Z, X)

**Comment by jingfengou** [comment]
Thanks very much!
