### ISSUE TITLE
Data prep for morphoMNIST & CelebAHQ

### ISSUE THREAD

**Issue by cianeastwood** [yulun-rayn/variational-causal-inference#3]
Are there instructions for preparing these datasets before running the corresponding bash scripts? :)

**Comment by yulun-rayn** [comment]
Thanks for the question! These datasets can be found here: https://osf.io/q6tpk/

For any future image datasets that you might be interested in, checkout the image dataset template in [image_dataset.py](https://github.com/yulun-rayn/variational-causal-inference/blob/main/vci/dataset/image_dataset.py). Essentially, you just need to 1) provide the path to image folder as argument, 2) provide paths to attributes and splits files as arguments, 3) modify `get_transform` method according to your specific needs for image transformation.

For a more flexible way to write your own image data class, checkout the base template in [base_dataset.py](https://github.com/yulun-rayn/variational-causal-inference/blob/main/vci/dataset/base_dataset.py). Both the CelebA-HQ data class ([celebA_dataset.py](https://github.com/yulun-rayn/variational-causal-inference/blob/main/vci/dataset/celebA_dataset.py)) and Morpho-MNIST data class ([morphoMNIST_dataset.py](https://github.com/yulun-rayn/variational-causal-inference/blob/main/vci/dataset/morphoMNIST_dataset.py)) in our implementation are written upon this base data class.
